name: Build and Upload Image

on:
  workflow_call:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: docker build . --tag placeholder

      - run: docker save placeholder -o /tmp/image.tar

      - uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: /tmp/image.tar
